-- Add PCN Articles Library articles to the posts table
-- These are categorized as "Leadership Formation" pillar since they're for pastors

INSERT INTO posts (title, slug, content, pillar, readTime, published, createdAt, updatedAt) VALUES

-- VOLUME 1 - PASTORAL HEALTH
('Why Pastors Quit (And How to Stay)', 'why-pastors-quit-and-how-to-stay', 'From the PCN Articles Library: Every year, thousands of pastors walk away from ministry. Some leave quietly. Others burn out in public. This article explores the real reasons pastors leave and what structures keep them in ministry long-term.', 'Leadership Formation', 9, true, NOW(), NOW()),
('The Hidden Pain of the Successful Pastor', 'hidden-pain-successful-pastor', 'From the PCN Articles Library: Success in ministry creates a peculiar kind of isolation. The larger your platform, the harder it becomes to be honest about your struggles. This article addresses the loneliness of visible success.', 'Leadership Formation', 8, true, NOW(), NOW()),
('Your Church Needs You Healthy More Than It Needs You Busy', 'church-needs-you-healthy-not-busy', 'From the PCN Articles Library: A pastor who gives without receiving will eventually have nothing left to give. This article explores why rest is not a reward but a requirement for sustainable ministry.', 'Leadership Formation', 8, true, NOW(), NOW()),
('How I Learned to Stop Performing and Start Pastoring', 'stop-performing-start-pastoring', 'From the PCN Articles Library: The drift into performance in ministry is gradual. This personal essay explores the journey from performance-driven ministry back to genuine pastoral care.', 'Leadership Formation', 9, true, NOW(), NOW()),
('Building a Personal Board of Accountability', 'personal-board-accountability', 'From the PCN Articles Library: Every CEO has a board. Most pastors do not. This article explores how to build a personal board of accountability for spiritual health and leadership.', 'Leadership Formation', 8, true, NOW(), NOW()),

-- VOLUME 1 - LEADERSHIP & MINISTRY
('The 5 Biggest Mistakes New Pastors Make', 'five-biggest-mistakes-new-pastors', 'From the PCN Articles Library: New pastors often arrive with genuine faith and calling but lack experience. This article names five predictable patterns of failure that veteran pastors can help new leaders avoid.', 'Leadership Formation', 9, true, NOW(), NOW()),
('How to Lead Through a Church Crisis', 'lead-through-church-crisis', 'From the PCN Articles Library: At some point in almost every pastor\'s tenure, a crisis arrives. How a pastor leads in crisis often defines their ministry more than anything they do in ordinary seasons.', 'Leadership Formation', 9, true, NOW(), NOW()),
('The Art of Saying No Without Guilt', 'art-of-saying-no-without-guilt', 'From the PCN Articles Library: Many pastors absorbed a theology of yes. Every need is a call. This article explores why saying no is not abandonment but prioritization.', 'Leadership Formation', 8, true, NOW(), NOW()),
('Building a Culture of Discipleship, Not Just Attendance', 'culture-discipleship-not-attendance', 'From the PCN Articles Library: The difference between a church that gathers people and a church that disciples people. This article explores what it takes to build a culture of genuine spiritual formation.', 'Leadership Formation', 8, true, NOW(), NOW()),
('What Bivocational Pastors Get Right That Full-Time Pastors Often Miss', 'bivocational-pastors-get-right', 'From the PCN Articles Library: Bivocational pastors operate from a different set of assumptions and often develop strengths that full-time pastors overlook. This article explores what those strengths are.', 'Leadership Formation', 8, true, NOW(), NOW()),

-- VOLUME 1 - UNITY & COLLABORATION
('Why I Stopped Competing With the Church Across Town', 'stopped-competing-church-across-town', 'From the PCN Articles Library: The competitive spirit in ministry is subtle and destructive. This article explores the shift from competition to collaboration in local church ministry.', 'Leadership Formation', 8, true, NOW(), NOW()),
('What I Learned From a Pastor Who Disagrees With Me Theologically', 'learned-from-pastor-disagrees', 'From the PCN Articles Library: Some of the most formative relationships in ministry are with pastors who see things differently. This article explores what unity looks like when theology differs.', 'Leadership Formation', 8, true, NOW(), NOW()),
('The Cost of Ministry Silos', 'cost-of-ministry-silos', 'From the PCN Articles Library: When churches operate in silos, the whole suffers. This article explores the relational and missional cost of fragmented ministry.', 'Leadership Formation', 7, true, NOW(), NOW()),
('How to Build Real Friendships With Other Pastors', 'build-real-friendships-other-pastors', 'From the PCN Articles Library: Genuine friendship among pastors is rare and essential. This article explores what it takes to move from professional acquaintance to genuine partnership.', 'Leadership Formation', 8, true, NOW(), NOW()),

-- VOLUME 1 - GLOBAL MISSION
('Why the Future of Missions Is Already There', 'future-of-missions-already-there', 'From the PCN Articles Library: The missionary landscape is shifting. This article explores how the church in the Global South is redefining what it means to be a missionary.', 'Leadership Formation', 8, true, NOW(), NOW()),
('What Partnering With a National Pastor Really Looks Like', 'partnering-national-pastor', 'From the PCN Articles Library: True partnership in missions looks different than many Western churches assume. This article explores what genuine collaboration with national pastors requires.', 'Leadership Formation', 8, true, NOW(), NOW()),
('Mobilizing Your Church for World Missions Without a Big Budget', 'mobilizing-church-missions-small-budget', 'From the PCN Articles Library: Limited resources do not mean limited impact in missions. This article explores how churches with small budgets can mobilize for global mission.', 'Leadership Formation', 8, true, NOW(), NOW()),

-- VOLUME 2 - PASTORAL HEALTH
('The Slow Burn: How Ministry Exhaustion Sneaks Up on You', 'slow-burn-ministry-exhaustion', 'From the PCN Articles Library: Burnout is not a moment—it is a process. This article explores the invisible, cumulative erosion that happens beneath the surface of ordinary productivity.', 'Leadership Formation', 9, true, NOW(), NOW()),
('What a Sabbatical Is — And Why Your Church Should Require One', 'sabbatical-why-church-should-require', 'From the PCN Articles Library: A sabbatical is an extended application of the biblical rhythm of rest. This article explores what sabbaticals produce and how to structure one.', 'Leadership Formation', 9, true, NOW(), NOW()),
('How to Return to Ministry After Burning Out', 'return-ministry-after-burnout', 'From the PCN Articles Library: The path back from burnout is not dramatic. This article explores what genuine recovery and re-entry into ministry looks like.', 'Leadership Formation', 8, true, NOW(), NOW()),
('The Difference Between Being Tired and Being Done', 'difference-tired-and-done', 'From the PCN Articles Library: Not all fatigue is the same. This article explores the critical distinction between normal tiredness and the depletion that signals a deeper crisis.', 'Leadership Formation', 8, true, NOW(), NOW()),
('When the Man in the Pulpit Is Falling Apart', 'when-man-pulpit-falling-apart', 'From the PCN Articles Library: What happens when a pastor\'s private crisis becomes public? This article explores how to lead through personal collapse with integrity.', 'Leadership Formation', 8, true, NOW(), NOW()),
('What Your Spouse Wishes You Knew About Life in the Parsonage', 'spouse-wishes-knew-parsonage', 'From the PCN Articles Library: Ministry marriages carry unique pressures. This article explores the spouse\'s perspective on pastoral life and what they need from their partner.', 'Leadership Formation', 8, true, NOW(), NOW()),
('Protecting Your Marriage When Ministry Demands Everything', 'protecting-marriage-ministry-demands', 'From the PCN Articles Library: The pastor\'s marriage is the first casualty of an unexamined theology of availability. This article explores how to protect what matters most.', 'Leadership Formation', 9, true, NOW(), NOW()),
('The Pastor\'s Kids Are Watching — What Are They Seeing?', 'pastors-kids-watching-what-seeing', 'From the PCN Articles Library: Pastoral children inherit both the gifts and the wounds of their parent\'s calling. This article explores what it means to pastor your own family well.', 'Leadership Formation', 8, true, NOW(), NOW()),
('How to Be Present at Home When Your Mind Never Leaves the Church', 'present-at-home-mind-never-leaves', 'From the PCN Articles Library: The challenge of mental disengagement from ministry. This article explores practical rhythms for being genuinely present with family.', 'Leadership Formation', 8, true, NOW(), NOW()),
('It\'s Okay to See a Counselor — Why Pastors Resist and Why They Shouldn\'t', 'okay-to-see-counselor', 'From the PCN Articles Library: Many pastors resist counseling due to shame or theological confusion. This article explores why professional help is not a failure of faith.', 'Leadership Formation', 8, true, NOW(), NOW()),
('What Pastors Need to Know About Depression (And Why It\'s Not a Faith Problem)', 'pastors-depression-not-faith-problem', 'From the PCN Articles Library: Depression in ministry is common and often misunderstood. This article explores what pastors need to know about mental health and faith.', 'Leadership Formation', 9, true, NOW(), NOW()),
('Anxiety, Perfectionism, and the Pastor: Breaking the Cycle', 'anxiety-perfectionism-pastor-breaking-cycle', 'From the PCN Articles Library: Many pastors are high-achievers with perfectionist tendencies. This article explores how perfectionism becomes a trap and how to break free.', 'Leadership Formation', 8, true, NOW(), NOW()),
('You Are Not Your Church\'s Attendance Numbers', 'not-your-churchs-attendance-numbers', 'From the PCN Articles Library: The pastor\'s identity becomes entangled with metrics. This article explores how to separate your worth from your church\'s performance.', 'Leadership Formation', 7, true, NOW(), NOW()),

-- VOLUME 2 - LEADERSHIP & MINISTRY
('How to Preach the Same Gospel to People Who Are Nothing Alike', 'preach-same-gospel-different-people', 'From the PCN Articles Library: Congregations are increasingly diverse. This article explores how to preach with fidelity to Scripture while speaking to radically different life experiences.', 'Leadership Formation', 9, true, NOW(), NOW()),
('When Your Preaching Gets Stale — and What to Do About It', 'when-preaching-gets-stale', 'From the PCN Articles Library: Even the best preachers hit seasons where the well runs dry. This article explores how to refresh your preaching and recover your joy in the pulpit.', 'Leadership Formation', 8, true, NOW(), NOW()),
('Five Sermon Habits That Are Slowly Shrinking Your Congregation\'s Faith', 'five-sermon-habits-shrinking-faith', 'From the PCN Articles Library: Some preaching patterns, however well-intentioned, actually diminish congregational faith. This article explores what those patterns are and how to change them.', 'Leadership Formation', 9, true, NOW(), NOW()),
('Preaching to the Room That\'s Not There Yet — How to Reach the Unchurched', 'preaching-to-room-not-there-yet', 'From the PCN Articles Library: How do you preach to Christians while also reaching the spiritually curious? This article explores how to hold both audiences at once.', 'Leadership Formation', 9, true, NOW(), NOW()),
('80% of Churches Are Plateaued or Declining — Are You One of Them?', 'eighty-percent-churches-plateaued', 'From the PCN Articles Library: Plateau is not failure—it\'s a diagnosis. This article explores what plateau means and what it takes to move beyond it.', 'Leadership Formation', 8, true, NOW(), NOW()),
('What Small Churches Get Right That Large Churches Rarely Talk About', 'small-churches-get-right', 'From the PCN Articles Library: Small churches possess strengths that large churches often lose. This article explores what those strengths are and why they matter.', 'Leadership Formation', 8, true, NOW(), NOW()),
('The Metrics That Actually Tell You if Your Church Is Healthy', 'metrics-tell-church-healthy', 'From the PCN Articles Library: Not all metrics matter equally. This article explores what actually indicates congregational health beyond attendance and giving.', 'Leadership Formation', 8, true, NOW(), NOW()),
('When Is It Time to Revitalize — and When Is It Time to Replant?', 'revitalize-or-replant', 'From the PCN Articles Library: Not every declining church should be revitalized. This article explores how to discern whether a church should be renewed or replanted.', 'Leadership Formation', 8, true, NOW(), NOW()),
('How to Lead a Church Through a Season of Decline Without Losing Hope', 'lead-church-decline-without-losing-hope', 'From the PCN Articles Library: Decline is painful and disorienting. This article explores how to lead with honesty and hope through seasons of contraction.', 'Leadership Formation', 9, true, NOW(), NOW()),
('How to Give Feedback That Actually Changes Behavior', 'give-feedback-changes-behavior', 'From the PCN Articles Library: Most feedback fails because it is poorly delivered. This article explores how to give feedback that people actually hear and act on.', 'Leadership Formation', 8, true, NOW(), NOW()),
('The Most Dangerous Person on a Church Staff (It Might Surprise You)', 'most-dangerous-person-church-staff', 'From the PCN Articles Library: Not all staff problems are obvious. This article explores the hidden dynamics that can undermine a healthy staff culture.', 'Leadership Formation', 8, true, NOW(), NOW()),
('When to Fire Someone — and How to Do It With Integrity', 'when-fire-someone-with-integrity', 'From the PCN Articles Library: Firing is never easy, but sometimes it is necessary. This article explores how to make that decision and carry it out with pastoral care.', 'Leadership Formation', 8, true, NOW(), NOW()),
('Building a Staff Culture Where People Don\'t Burn Out and Leave', 'staff-culture-no-burnout', 'From the PCN Articles Library: Staff turnover is expensive and disruptive. This article explores what creates a culture where good people stay and thrive.', 'Leadership Formation', 9, true, NOW(), NOW()),
('What Gen Z Actually Wants From a Church (And Why It\'s Not What You Think)', 'gen-z-wants-from-church', 'From the PCN Articles Library: Generational assumptions often mislead. This article explores what Gen Z actually seeks in a church community.', 'Leadership Formation', 8, true, NOW(), NOW()),
('Why Young Adults Are Coming Back to Church — and How Not to Lose Them Again', 'young-adults-coming-back-church', 'From the PCN Articles Library: Young adults are returning to church in surprising numbers. This article explores what is drawing them back and what keeps them away.', 'Leadership Formation', 8, true, NOW(), NOW()),

-- VOLUME 2 - UNITY & COLLABORATION
('What the Scandals in the Church Are Teaching Us About Accountability', 'scandals-teaching-accountability', 'From the PCN Articles Library: Recent crises have exposed accountability failures. This article explores what the church is learning about structures that prevent abuse.', 'Leadership Formation', 9, true, NOW(), NOW()),
('How to Talk About Political Divisiveness From the Pulpit Without Destroying Your Church', 'talk-politics-pulpit-without-destroying', 'From the PCN Articles Library: Political division is tearing churches apart. This article explores how to address the elephant in the room with wisdom and care.', 'Leadership Formation', 9, true, NOW(), NOW()),
('When a Church Split Happens — Surviving It, Learning From It, Moving Forward', 'church-split-surviving-learning-forward', 'From the PCN Articles Library: Church splits are traumatic and often preventable. This article explores how to navigate them with integrity and grace.', 'Leadership Formation', 9, true, NOW(), NOW()),
('Reformed and Charismatic Pastors at the Same Table — What Happened When We Tried', 'reformed-charismatic-pastors-same-table', 'From the PCN Articles Library: Theological diversity can strengthen or fracture. This article explores what happened when pastors from different traditions genuinely listened.', 'Leadership Formation', 8, true, NOW(), NOW()),
('The Case for Doing City-Wide Church Together at Least Once a Year', 'city-wide-church-together', 'From the PCN Articles Library: Local church unity is more than a nice idea. This article explores what happens when churches in a city actually gather as one.', 'Leadership Formation', 8, true, NOW(), NOW()),
('What a Healthy Pastor Referral Network Actually Looks Like', 'healthy-pastor-referral-network', 'From the PCN Articles Library: Pastors need each other for referrals and support. This article explores what a functioning referral network requires.', 'Leadership Formation', 8, true, NOW(), NOW()),
('How Three Small Churches Co-Planted One New Congregation', 'three-small-churches-coplanted', 'From the PCN Articles Library: Collaboration in church planting multiplies impact. This article explores how three small churches partnered to plant something new.', 'Leadership Formation', 8, true, NOW(), NOW()),
('Before You Launch That Ministry, Ask If Another Church in Town Is Already Doing It', 'before-launch-ministry-ask-other-church', 'From the PCN Articles Library: Duplication of effort wastes resources. This article explores how to collaborate rather than compete in ministry.', 'Leadership Formation', 7, true, NOW(), NOW()),
('What Predominantly White Churches Get Wrong When They Talk About Diversity', 'white-churches-wrong-about-diversity', 'From the PCN Articles Library: Diversity conversations often miss the mark. This article explores what white church leaders need to understand about genuine inclusion.', 'Leadership Formation', 9, true, NOW(), NOW()),
('What I Learned About Unity From Pastoring Across Cultural Lines', 'learned-unity-pastoring-across-cultures', 'From the PCN Articles Library: Cross-cultural ministry teaches lessons about unity that homogeneous churches miss. This article explores those lessons.', 'Leadership Formation', 8, true, NOW(), NOW()),

-- VOLUME 2 - GLOBAL MISSION
('Church Closures Are Outpacing Church Plants 3 to 1 — What That Means for the Mission', 'church-closures-outpacing-plants', 'From the PCN Articles Library: The American church landscape is contracting. This article explores what that means for the mission and how to respond.', 'Leadership Formation', 8, true, NOW(), NOW()),
('How to Talk About Global Missions in a Way That Actually Moves Your Congregation', 'talk-global-missions-moves-congregation', 'From the PCN Articles Library: Missions talks often fall flat. This article explores how to communicate about global mission in ways that actually inspire action.', 'Leadership Formation', 8, true, NOW(), NOW()),
('When Short-Term Mission Trips Help and When They Hurt', 'short-term-mission-trips-help-hurt', 'From the PCN Articles Library: Short-term missions are controversial for good reason. This article explores when they serve the mission and when they undermine it.', 'Leadership Formation', 9, true, NOW(), NOW()),
('The Unreached People Groups Closest to You That You\'ve Never Considered', 'unreached-people-groups-closest-to-you', 'From the PCN Articles Library: Global mission starts closer than we think. This article explores unreached groups in your own community.', 'Leadership Formation', 8, true, NOW(), NOW()),
('How National Pastors Are Redefining What It Means to Be a Missionary', 'national-pastors-redefining-missionary', 'From the PCN Articles Library: The missionary movement is shifting. This article explores how national pastors are leading the mission in their own contexts.', 'Leadership Formation', 8, true, NOW(), NOW()),
('What the Church in the Global South Can Teach the Church in America About Suffering', 'global-south-church-teach-suffering', 'From the PCN Articles Library: The persecuted church has wisdom about faith that the comfortable church needs. This article explores what that wisdom is.', 'Leadership Formation', 8, true, NOW(), NOW()),
('Building a Mission-Sending Culture in a Church That\'s Never Sent Anyone', 'mission-sending-culture-never-sent', 'From the PCN Articles Library: Mission culture does not happen by accident. This article explores how to build it intentionally in a church with no sending tradition.', 'Leadership Formation', 8, true, NOW(), NOW()),

-- VOLUME 2 - CHURCH & CULTURE
('How to Pastor a Congregation That Is Politically Divided — And Keep the Gospel Central', 'pastor-politically-divided-gospel-central', 'From the PCN Articles Library: Political division is the defining challenge of contemporary pastoring. This article explores how to lead through it with gospel clarity.', 'Leadership Formation', 9, true, NOW(), NOW()),
('Engaging the \'Nones\' — What Research Tells Us About Reaching the Religiously Unaffiliated', 'engaging-nones-religiously-unaffiliated', 'From the PCN Articles Library: The religiously unaffiliated are growing. This article explores what research tells us about reaching them.', 'Leadership Formation', 8, true, NOW(), NOW()),
('AI, Authenticity, and the Pastor: What Artificial Intelligence Means for Ministry', 'ai-authenticity-pastor-artificial-intelligence', 'From the PCN Articles Library: AI is changing communication. This article explores what it means for pastoral authenticity and ministry.', 'Leadership Formation', 8, true, NOW(), NOW()),
('When the Church Becomes a Political Brand — and How to Step Back From the Edge', 'church-political-brand-step-back', 'From the PCN Articles Library: The church risks becoming a political brand. This article explores how to recover gospel clarity and prophetic distance.', 'Leadership Formation', 9, true, NOW(), NOW()),
('How to Lead When Trust in Institutions — Including the Church — Is at an All-Time Low', 'lead-when-trust-institutions-low', 'From the PCN Articles Library: Institutional trust is eroding. This article explores how to lead with integrity when people are skeptical of all institutions.', 'Leadership Formation', 9, true, NOW(), NOW());
