-- Insert 100 Prophetic Justice Articles into posts table
-- All articles are categorized as Prophetic Justice pillar, general audience

INSERT INTO posts (title, slug, excerpt, content, pillar, author, status, readTime, contentType, audienceType, createdAt, updatedAt) VALUES

-- SECTION 1: HISTORICAL SILENCE & CREDIBILITY (1-10)
('Where the Church Was Silent', 'where-church-was-silent', 'A reckoning with the history of silence during slavery, Jim Crow, and civil rights. The church''s institutional interests created powerful incentives for silence.', 'The church in America has a history that is not primarily the history of courage and faithfulness. It is, in significant stretches, a history of silence in the face of injustice. The silence during chattel slavery, Jim Crow, and the civil rights movement reveals a pattern of institutional self-preservation over prophetic faithfulness.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

('Justice Is Not a Political Category', 'justice-not-political', 'Justice appears 400+ times in the OT. It describes God''s character and what God requires. The prophets announced justice as theology, not politics.', 'The word "justice" came to be heard in many evangelical contexts as a political term. This inversion is theological error of the most significant kind. Mishpat describes God''s own character, God''s activity in history, and the specific disposition that God requires of God''s people.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('Complicity Is Not Innocence', 'complicity-not-innocence', 'Silence in the face of injustice is not neutrality. It is a specific moral choice with specific moral consequences.', 'The comfortable Christian position in a culture with genuine injustice is neither endorsement nor active resistance. It is something more subtle and more convenient: the claim of non-involvement. This position presents itself as principled. It is, on examination, a specific kind of complicity.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

('The Poor Are Not a Ministry Category', 'poor-not-ministry', 'They are the test of the church. Matthew 25 reveals where the risen Christ is to be found.', 'The biblical position on the poor is not ambiguous. It is among the most consistently stated themes in the entire canon of Scripture. The test of genuine Christian devotion is not the quality of the worship service. It is the quality of the care for the vulnerable.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('Creation Care Is Not Optional', 'creation-care-not-optional', 'Environmental stewardship is embedded in the creation mandate and the prophetic tradition.', 'Creation care is not an optional add-on to Christian faith but central to God''s purposes. The church that preaches about God''s creation while being indifferent to its destruction has separated theology from reality.', 'Prophetic Justice', 'James Bell', 1, 6, 'general', 'general', NOW(), NOW()),

('The Widow, the Orphan, the Stranger', 'widow-orphan-stranger', 'These three categories appear throughout Scripture as the specific focus of God''s justice concern.', 'These three categories—the widow, the orphan, the stranger—appear repeatedly throughout Scripture as the specific focus of God''s justice concern. They represent the vulnerable, the powerless, the ones without advocate or protection.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('Mishpat and Tsedaqah', 'mishpat-tsedaqah', 'Understanding the Hebrew words that describe God''s justice and righteousness.', 'Mishpat and tsedaqah are the two Hebrew words that describe God''s justice and righteousness. Mishpat is the active work of justice. Tsedaqah is the right relationship that results from justice. Together they describe God''s character and what God requires.', 'Prophetic Justice', 'James Bell', 1, 6, 'general', 'general', NOW(), NOW()),

('What Micah 6:8 Actually Demands', 'micah-6-8-demands', '"Act justly, love mercy, walk humbly" is not optional advice but the core requirement of following God.', 'He has shown you, O mortal, what is good. And what does the LORD require of you? To act justly and to love mercy and to walk humbly with your God. This is not optional advice. It is the core requirement of following God.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('The Church Has a Credibility Problem', 'church-credibility-problem', 'The cost of silence is the loss of credibility with the very people the church claims to care about.', 'The church known, among the people it claims to care about, for its silence when they needed its voice has sacrificed something very difficult to recover—the credibility that comes from being genuinely trustworthy in the moments that matter.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

('Why Racial Reconciliation Without Repentance Is Just Branding', 'racial-reconciliation-without-repentance', 'Genuine reconciliation requires material restitution, not just spiritual apologies.', 'Racial reconciliation without repentance is just branding. Genuine reconciliation requires material restitution, not just spiritual apologies. The church that advocates forgiveness without engaging the question of restitution has received only half the biblical witness.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

-- SECTION 2: ECONOMIC JUSTICE & POVERTY (11-20)
('The Prophetic Tradition on Economic Justice', 'prophetic-tradition-economic-justice', 'Amos, Isaiah, Jeremiah all spoke with specificity about economic systems and the treatment of the poor.', 'The Hebrew prophets were not social activists who occasionally mentioned God. They were messengers of God who announced, with extraordinary specificity, what God thought about the social arrangements of Israel—about the treatment of the poor, the widow, the orphan, the immigrant.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

('What the Jubilee Means', 'what-jubilee-means', 'A radical economic reset that returns land and forgives debts. What would jubilee look like in the American context?', 'The Jubilee was a radical economic reset. Every fifty years, land returned to its original owners and debts were forgiven. It was God''s way of preventing the permanent accumulation of wealth and power in the hands of the few.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('The Stranger at the Gate', 'stranger-at-gate', 'Immigration is a theological issue rooted in God''s identification with the vulnerable.', 'Immigration is not primarily a political issue but a theological one. The stranger at the gate is the specific focus of God''s justice concern throughout Scripture. The church''s response to immigration reveals its actual theology.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('Individual Sin Is Real — But So Is Systemic Sin', 'individual-sin-systemic-sin', 'The Bible addresses both personal morality and structural injustice.', 'The Bible addresses both individual sin and systemic sin. The prophets condemned individual greed but also the systems that made greed profitable. The church that addresses only individual sin while ignoring systemic injustice has misunderstood the prophetic tradition.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

('Why Poverty Is Political', 'why-poverty-political', 'Poverty is not primarily a result of individual failure but of systems that concentrate wealth and opportunity.', 'Poverty is not primarily a result of individual failure but of systems that concentrate wealth and opportunity. The distribution of poverty along racial and economic lines reveals that it is the result of systems, not individual choices.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('The Church''s Wealth and the World''s Poverty', 'church-wealth-world-poverty', 'The distribution of resources between the American church and global poverty reveals our actual priorities.', 'The American church is extraordinarily wealthy. The global church is largely poor. The distribution of resources between them reveals our actual priorities more clearly than any statement of theology.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('Why Payday Lending Should Keep Christians Up at Night', 'payday-lending-christians', 'A system that extracts wealth from the poor is incompatible with Christian ethics.', 'Payday lending is a system that extracts wealth from the poor. It is incompatible with Christian ethics rooted in God''s identification with the vulnerable. The church''s silence on payday lending is a moral failure.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('The Silence About Abuse in the Church', 'silence-abuse-church', 'Institutional protection of abusers reveals the church''s prioritization of institutional reputation over victim protection.', 'The church''s response to abuse reveals its actual priorities. The institutional protection of abusers shows that the church prioritizes its own reputation over the protection of the vulnerable.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

('Imago Dei Means More Than You Think', 'imago-dei-means', 'If every person bears God''s image, then the treatment of the poor, the imprisoned, the marginalized is treatment of God.', 'If every person bears God''s image, then the treatment of the poor, the imprisoned, the marginalized is treatment of God. The imago Dei is not just a theological concept but a claim about how we must treat every person.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('What the Good Samaritan Is Actually Arguing', 'good-samaritan-actually-arguing', 'The parable is not primarily about individual charity but about crossing boundaries to care for the vulnerable.', 'The parable of the Good Samaritan is not primarily about individual charity. It is about crossing boundaries—ethnic, religious, social—to care for the vulnerable. It is a parable about justice, not just kindness.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

-- SECTION 3: SOLIDARITY, RACE & VULNERABLE POPULATIONS (21-30)
('Why Solidarity Is a Theological Virtue', 'solidarity-theological-virtue', 'Standing with the vulnerable is not optional activism but a core expression of Christian faith.', 'Solidarity is not optional activism but a core expression of Christian faith. Standing with the vulnerable is a theological virtue rooted in God''s identification with the oppressed.', 'Prophetic Justice', 'James Bell', 1, 6, 'general', 'general', NOW(), NOW()),

('The Most Prophetic Thing You Can Do Is Live Differently', 'prophetic-thing-live-differently', 'Prophetic witness includes the material choices about how we live.', 'The most prophetic thing you can do is live differently. Prophetic witness includes the material choices about how we live—what we consume, where we live, how we spend our money.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('Why Children in Poverty Are a Prophetic Indictment', 'children-poverty-prophetic-indictment', 'Jesus''s teaching about children reveals that their treatment is a measure of the kingdom.', 'Jesus''s teaching about children reveals that their treatment is a measure of the kingdom. Children in poverty are not a charity issue. They are a prophetic indictment of systems that allow children to suffer.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('Why Addressing Symptoms Without Causes Is Charity, Not Justice', 'symptoms-without-causes', 'Feeding the hungry is necessary but insufficient without addressing the systems that create hunger.', 'Feeding the hungry is necessary but insufficient without addressing the systems that create hunger. Charity addresses symptoms. Justice addresses systems. The church must do both.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('The Church and Mental Health Justice', 'church-mental-health-justice', 'Mental health access is distributed along the same lines as every other form of inequality.', 'Mental health access is distributed along the same lines as every other form of inequality. The church''s response to mental health reveals its actual theology of care for the vulnerable.', 'Prophetic Justice', 'James Bell', 1, 6, 'general', 'general', NOW(), NOW()),

('Church Megaproject Budgets and the Widow''s Mite', 'church-megaproject-widow-mite', 'The contrast between institutional spending and individual sacrifice reveals priorities.', 'The contrast between church megaproject budgets and the widow''s mite reveals priorities. Jesus praised the widow not because her gift was large but because it cost her everything. What does our spending reveal about what we value?', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

('What Predominantly White Churches Get Wrong About Diversity', 'white-churches-diversity-wrong', 'Diversity without power-sharing is tokenism, not justice.', 'Diversity without power-sharing is tokenism, not justice. The church that celebrates diversity while maintaining white leadership and white theology has not addressed the systems of power that created segregation.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

('Why "Reaching the Rich" Has Always Been More Comfortable', 'reaching-rich-more-comfortable', 'The church''s institutional bias toward the wealthy is a theological problem.', 'The church''s institutional bias toward the wealthy is a theological problem. The pastor who reaches the rich faces no institutional resistance. The pastor who reaches the poor faces institutional suspicion.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('The Theology of Repair', 'theology-of-repair', 'Restorative justice is rooted in God''s commitment to making right what was made wrong.', 'Restorative justice is rooted in God''s commitment to making right what was made wrong. The theology of repair is not optional but central to the gospel.', 'Prophetic Justice', 'James Bell', 1, 6, 'general', 'general', NOW(), NOW()),

('Hospitality Is Not Optional', 'hospitality-not-optional', 'The biblical mandate to welcome the stranger is a core expression of justice.', 'The biblical mandate to welcome the stranger is a core expression of justice. Hospitality is not optional but a requirement of following God. The church that closes its doors to the stranger has closed its doors to Christ.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

-- SECTION 4: STRUCTURAL JUSTICE & CREATION CARE (31-40)
('Disability Justice Is a Theological Issue', 'disability-justice-theological', 'The inclusion of people with disabilities is not charity but justice rooted in the imago Dei.', 'The inclusion of people with disabilities is not charity but justice rooted in the imago Dei. The church that excludes people with disabilities has excluded people who bear God''s image.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('The Earth Is the Lord''s', 'earth-is-lords', 'Creation care is not an optional add-on to Christian faith but central to God''s purposes.', 'The earth is the Lord''s. Creation care is not an optional add-on to Christian faith but central to God''s purposes. The church that preaches about God''s creation while being indifferent to its destruction has separated theology from reality.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('What the Book of Ruth Says About Gleaning Laws', 'book-ruth-gleaning-laws', 'Economic systems can be designed to include the vulnerable.', 'The gleaning laws in Leviticus and Ruth reveal that economic systems can be designed to include the vulnerable. The poor were not excluded from provision but included through specific legal protections.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('Why the Church''s Comfort With Inequality Requires Explanation', 'church-comfort-inequality', 'Massive inequality is not normal or inevitable but the result of systems that can be changed.', 'Massive inequality is not normal or inevitable but the result of systems that can be changed. The church''s comfort with inequality requires explanation. It is not compatible with a theology rooted in God''s justice.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

('The Prophetic Pastor', 'prophetic-pastor', 'What it looks like for pastors to speak prophetically in their own contexts.', 'The prophetic pastor is not primarily a political activist but a pastor who speaks truthfully about what God requires in the specific context where God has placed them.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('Justice Without Love Is Ideology', 'justice-without-love-ideology', 'Justice pursued without love becomes its own form of oppression.', 'Justice without love is ideology. Love without justice is sentimentality. The prophets combined both—fierce justice pursued in the context of profound love for the people.', 'Prophetic Justice', 'James Bell', 1, 6, 'general', 'general', NOW(), NOW()),

('What the Beatitudes Are Actually Promising', 'beatitudes-actually-promising', 'Jesus''s vision of the kingdom includes material reversal and the exaltation of the vulnerable.', 'The Beatitudes are not promises of spiritual comfort but of material reversal. Blessed are the poor. Blessed are those who hunger. Blessed are those who mourn. Jesus''s vision of the kingdom includes the exaltation of the vulnerable.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

('The Black Church Has Been Doing Prophetic Justice for Centuries', 'black-church-prophetic-justice', 'The prophetic tradition is alive in Black church theology and practice.', 'The Black church has been doing prophetic justice for centuries. The prophetic tradition is alive in Black church theology and practice. The white church has much to learn from the Black church about faithfulness.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

('Why Color-Blindness Is Not a Theological Virtue', 'color-blindness-not-virtue', 'Ignoring racial difference ignores the specific ways injustice operates.', 'Color-blindness is not a theological virtue. Ignoring racial difference ignores the specific ways injustice operates. The church must see race in order to address racism.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('The Most Vulnerable People in Your City Are Not in Your Pews', 'vulnerable-people-not-pews', 'The church''s insularity prevents it from encountering the people most affected by injustice.', 'The most vulnerable people in your city are not in your pews. The church''s insularity prevents it from encountering the people most affected by injustice. This is a theological problem.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

-- SECTION 5: PROPHETIC VOICE & THE LONG ARC (41-50)
('Why the Prophets Were Expelled From the Sanctuary', 'prophets-expelled-sanctuary', 'Prophetic speech that disrupts the comfortable religious culture is always rejected by institutions.', 'The prophets were expelled from the sanctuary because their speech disrupted the comfortable religious culture. Prophetic speech that disrupts is always rejected by institutions. This is not a bug. It is a feature.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

('What the Exodus Demands of the Church Today', 'exodus-demands-church', 'The Exodus is not just history but a pattern for God''s liberation of the oppressed.', 'The Exodus is not just history but a pattern for God''s liberation of the oppressed. God hears the cry of the enslaved. God acts to liberate. The church that ignores the Exodus has ignored a central pattern in God''s activity.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

('Sabbath Is Resistance', 'sabbath-is-resistance', 'Rest is a refusal to participate in systems of endless production and consumption.', 'Sabbath is resistance. Rest is a refusal to participate in systems of endless production and consumption. The church that does not practice Sabbath has accepted the logic of capitalism.', 'Prophetic Justice', 'James Bell', 1, 6, 'general', 'general', NOW(), NOW()),

('The Pastoral Care of the Wealthy Congregant', 'pastoral-care-wealthy', 'Pastors must help wealthy people understand the spiritual danger of wealth.', 'The pastoral care of the wealthy congregant is to help them understand the spiritual danger of wealth. Jesus spoke more about the spiritual danger of wealth than about any other single topic except the kingdom of God.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

('Why the Church''s Response to Poverty Has Been Mostly Charity', 'church-response-poverty-charity', 'Charity addresses symptoms; justice addresses systems.', 'Charity addresses symptoms. Justice addresses systems. The church''s response to poverty has been mostly charity. This is necessary but insufficient. The church must also address systems.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('What Leviticus 19 Demands in a Border Crisis', 'leviticus-19-border-crisis', 'The biblical law protects the stranger and demands fair treatment of immigrants.', 'Leviticus 19 demands that the stranger be treated as a native-born. The law protects the stranger and demands fair treatment of immigrants. This is not optional but a core requirement of following God.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

('The Church''s Incarceration Silence', 'church-incarceration-silence', 'Mass incarceration is a justice issue the church has largely ignored.', 'Mass incarceration is a justice issue the church has largely ignored. The church that preaches about redemption while being silent about a system that destroys millions has failed its prophetic calling.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

('Why the Church Must Speak About Housing', 'church-must-speak-housing', 'Housing is not a commodity but a human right rooted in God''s provision.', 'Housing is not a commodity but a human right rooted in God''s provision. The church that is silent about homelessness while preaching about God''s care has separated theology from reality.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('What We Owe the Ones Who Come After', 'what-we-owe-ones-after', 'Intergenerational justice requires that we address the systems we are leaving behind.', 'Intergenerational justice requires that we address the systems we are leaving behind. We are not free to ignore the future. We are accountable to the generations that come after.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('The Long Arc', 'the-long-arc', 'Justice is not achieved in a moment but through sustained prophetic faithfulness across generations.', 'Justice is not achieved in a moment but through sustained prophetic faithfulness across generations. The prophetic tradition is the tradition of the long arc—the commitment to justice that persists even when victory is not in sight.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

-- SECTION 6: WATER, REPARATIONS, FOOD & ECONOMIC TRUTH (51-60)
('Water Is a Theological Issue', 'water-theological-issue', 'Water appears on the first page of the Bible and the last. Access to clean water is a justice issue.', 'Water appears on the first page of the Bible and the last. Water is architecturally central to Scripture. Yet 785 million people lack access to clean drinking water. This is a theological issue.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

('The Theology of Reparations', 'theology-of-reparations', 'The Bible''s position on restitution is considerably more developed than most American Christians realize.', 'The concept of reparations provokes immediate resistance in most American evangelical contexts. Yet the Bible''s position on restitution is considerably more developed than most American Christians realize.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

('Food Deserts and the Theology of Bread', 'food-deserts-theology-bread', 'Jesus taught us to pray for daily bread. Food deserts deny this prayer to millions.', 'Approximately 23.5 million Americans live in food deserts. The theology of bread runs through the entire biblical narrative. The existence of food deserts is a contradiction of this theology.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

('Why the Church Talks About Sex More Than Money', 'church-sex-more-than-money', 'The Bible contains 2,350 verses about money but the church prioritizes sexual ethics.', 'The Bible contains roughly 2,350 verses about money, wealth, poverty, and economic justice. It contains considerably fewer about sexual ethics. Yet the church''s engagement with economic ethics has been comparatively thin.', 'Prophetic Justice', 'James Bell', 1, 9, 'general', 'general', NOW(), NOW()),

('Human Trafficking and Selective Outrage', 'human-trafficking-selective-outrage', 'The church''s response to trafficking reveals its actual priorities regarding vulnerable women.', 'Human trafficking is a justice issue. The church''s response to trafficking reveals its actual priorities regarding vulnerable women. Selective outrage about trafficking while ignoring other forms of exploitation is theological inconsistency.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

('The Doctrine of Discovery', 'doctrine-of-discovery', 'The theological justification for colonialism continues to shape American Christianity.', 'The Doctrine of Discovery was the theological justification for colonialism. It continues to shape American Christianity. The church must reckon with this history.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('Environmental Racism', 'environmental-racism', 'Pollution and environmental degradation are distributed along racial and economic lines.', 'Pollution and environmental degradation are distributed along racial and economic lines. Environmental racism is a justice issue rooted in systems that concentrate pollution in poor communities of color.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('The Theology of Fair Wages', 'theology-fair-wages', 'Deuteronomy demands that workers be paid fairly. Wage theft is theft.', 'Deuteronomy demands that workers be paid fairly. Wage theft is theft. The church that is silent about wage theft has failed its prophetic calling.', 'Prophetic Justice', 'James Bell', 1, 6, 'general', 'general', NOW(), NOW()),

('Healthcare as a Moral Issue', 'healthcare-moral-issue', 'Healthcare access is distributed along the same lines as every other form of inequality.', 'Healthcare access is distributed along the same lines as every other form of inequality. Healthcare is not a commodity but a human right rooted in God''s commitment to the flourishing of all people.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('What James 5 Actually Says', 'what-james-5-says', 'James''s condemnation of the wealthy who exploit workers is direct and unambiguous.', 'James 5 is James''s condemnation of the wealthy who exploit workers. It is direct and unambiguous. The church that ignores James 5 has ignored a core biblical witness to economic justice.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

-- SECTION 7: VIOLENCE, EDUCATION, DISPLACEMENT & POWER (61-70)
('The Church and Gun Violence', 'church-gun-violence', 'The church''s silence on gun violence is a moral failure.', 'Gun violence is a justice issue. The church''s silence on gun violence is a moral failure. The church that preaches about the sanctity of life while being silent about gun violence has separated theology from reality.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('Education Inequality', 'education-inequality', 'School funding based on property taxes ensures that poor communities have the worst schools.', 'School funding based on property taxes ensures that poor communities have the worst schools. Education inequality is a justice issue rooted in systems that concentrate resources in wealthy communities.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('Gentrification and Displacement', 'gentrification-displacement', 'Gentrification is not inevitable but the result of systems that prioritize profit over community.', 'Gentrification is not inevitable but the result of systems that prioritize profit over community. Displacement is a justice issue rooted in economic systems that extract wealth from poor communities.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('The Prosperity Gospel as Injustice Theology', 'prosperity-gospel-injustice', 'The prosperity gospel is not just wrong theology but active harm to the poor.', 'The prosperity gospel is not just wrong theology but active harm to the poor. It is a theology that blames the poor for their poverty and justifies the wealth of the rich.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('Missions Without Justice Is Colonialism', 'missions-without-justice-colonialism', 'Missionary work that does not address systemic injustice repeats colonial patterns.', 'Missions without justice is colonialism. Missionary work that does not address systemic injustice repeats colonial patterns. The church must examine its missionary practice.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('The Theology of Land', 'theology-of-land', 'Land is not a commodity but a gift from God, and land theft is a core injustice.', 'Land is not a commodity but a gift from God. Land theft is a core injustice rooted in colonialism. The church must reckon with the land on which it stands.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('What Nehemiah Teaches About Rebuilding', 'nehemiah-rebuilding', 'Rebuilding requires addressing the systems of exploitation that destroyed the community.', 'Nehemiah teaches that rebuilding requires addressing the systems of exploitation that destroyed the community. Justice is not just individual conversion but systemic transformation.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

('The Church and the Death Penalty', 'church-death-penalty', 'The death penalty is a justice issue rooted in the value of every human life.', 'The death penalty is a justice issue rooted in the value of every human life. The church that preaches about redemption while supporting the death penalty has separated theology from practice.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

('The Digital Divide', 'digital-divide', 'Access to technology and internet is distributed along the same lines as every other form of inequality.', 'The digital divide is a justice issue. Access to technology and internet is distributed along the same lines as every other form of inequality. This has profound implications for education and economic opportunity.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('Moral Injury and Veterans', 'moral-injury-veterans', 'Veterans who have committed acts they believe are immoral need communities of healing, not judgment.', 'Moral injury is a real phenomenon affecting veterans. Veterans who have committed acts they believe are immoral need communities of healing, not judgment. The church must respond with compassion.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

-- SECTION 8: PROTEST, PUBLIC SQUARE & PROPHETIC WITNESS (71-80)
('The Theology of Protest', 'theology-of-protest', 'Protest is not un-Christian but a form of prophetic witness rooted in God''s justice.', 'Protest is not un-Christian but a form of prophetic witness rooted in God''s justice. The prophets protested. Jesus protested. The church that condemns protest has condemned the prophetic tradition.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('Why the Church Abandoned the Public Square', 'church-abandoned-public-square', 'The church''s retreat from public engagement is a theological failure.', 'The church''s retreat from public engagement is a theological failure. The church that abandons the public square has abandoned its prophetic calling.', 'Prophetic Justice', 'James Bell', 1, 6, 'general', 'general', NOW(), NOW()),

('Maternal Mortality and the Pro-Life Blind Spot', 'maternal-mortality-pro-life', 'Pro-life theology that does not address maternal mortality is incomplete.', 'Maternal mortality is a justice issue. Pro-life theology that does not address maternal mortality is incomplete. The church must be pro-life in a comprehensive sense.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('What Isaiah 58 Demands', 'isaiah-58-demands', 'The fast God requires is not religious ceremony but the loosing of unjust bonds.', 'Isaiah 58 is God''s response to the people who fast but ignore injustice. The fast God requires is not religious ceremony but the loosing of unjust bonds. This is the core of the prophetic tradition.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

('The Church and the Refugee Crisis', 'church-refugee-crisis', 'Refugees are not a political issue but a theological one rooted in God''s identification with the vulnerable.', 'Refugees are not a political issue but a theological one rooted in God''s identification with the vulnerable. The church that closes its doors to refugees has closed its doors to Christ.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

('Elder Abuse and the Invisible Vulnerable', 'elder-abuse-invisible', 'Elder abuse is a justice issue that the church has largely ignored.', 'Elder abuse is a justice issue that the church has largely ignored. The church that preaches about honoring elders while being silent about elder abuse has separated theology from reality.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('Worship Without Justice Is Noise', 'worship-without-justice-noise', 'Amos''s condemnation of worship divorced from justice applies to contemporary churches.', 'Amos condemned worship divorced from justice. He called it noise. Amos''s condemnation applies to contemporary churches. Worship without justice is noise.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('The Theological Case Against Torture', 'theological-case-against-torture', 'Torture is incompatible with Christian theology rooted in the imago Dei.', 'Torture is incompatible with Christian theology rooted in the imago Dei. The church that supports torture has betrayed the gospel.', 'Prophetic Justice', 'James Bell', 1, 6, 'general', 'general', NOW(), NOW()),

('Food Sovereignty and the Theology of the Table', 'food-sovereignty-theology-table', 'The ability to feed oneself is a justice issue and a form of power.', 'Food sovereignty is a justice issue. The ability to feed oneself is a form of power. The church that ignores food sovereignty has ignored a core dimension of justice.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('What Amos Would Say to the American Church', 'amos-american-church', 'Amos''s indictments of the wealthy who exploit the poor speak directly to contemporary America.', 'Amos spoke to a society of wealth and inequality. His indictments speak directly to contemporary America. The church must listen to what Amos would say.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

-- SECTION 9: WAGES, ADDICTION, BORDERS & SYSTEMIC RECKONING (81-90)
('The Church and Wage Theft', 'church-wage-theft', 'Wage theft is theft. The church''s silence on this is a moral failure.', 'Wage theft is theft. The church''s silence on wage theft is a moral failure. The church that preaches about honesty while being silent about wage theft has separated theology from practice.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('Addiction Is a Justice Issue', 'addiction-justice-issue', 'Addiction is not primarily a moral failure but a symptom of systems that create desperation.', 'Addiction is not primarily a moral failure but a symptom of systems that create desperation. The church that condemns addiction without addressing the systems that create it has failed its prophetic calling.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

('The Theology of Borders', 'theology-of-borders', 'Borders are human constructions, not divine mandates. God''s justice transcends borders.', 'Borders are human constructions, not divine mandates. God''s justice transcends borders. The church that prioritizes borders over justice has made an idolatrous choice.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('Redlining, the Church, and the Neighborhoods We Made', 'redlining-church-neighborhoods', 'Redlining created the segregated neighborhoods we see today. The church was complicit.', 'Redlining created the segregated neighborhoods we see today. The church was complicit. The church must reckon with this history and its ongoing consequences.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

('What Psalm 82 Says About Unjust Systems', 'psalm-82-unjust-systems', 'God stands in judgment against systems that oppress the weak and needy.', 'Psalm 82 reveals God standing in judgment against systems that oppress the weak and needy. God is not neutral about injustice. The church must not be neutral either.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('The Church and Domestic Violence', 'church-domestic-violence', 'Domestic violence is a justice issue that the church has enabled through its theology of submission.', 'Domestic violence is a justice issue that the church has enabled through its theology of submission. The church must repent of its complicity and become a place of safety.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

('Climate Refugees', 'climate-refugees', 'Climate change will create millions of refugees. The church must prepare to respond.', 'Climate change will create millions of refugees. The church must prepare to respond. This is a justice issue rooted in the church''s responsibility to the vulnerable.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('Poverty Tourism Is Not Mission', 'poverty-tourism-not-mission', 'Mission that does not address systemic injustice is tourism that exploits the poor.', 'Poverty tourism is not mission. Mission that does not address systemic injustice is tourism that exploits the poor. The church must examine its missionary practice.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('The Theology of Public Health', 'theology-public-health', 'Public health is a justice issue rooted in God''s commitment to the flourishing of all people.', 'Public health is a justice issue rooted in God''s commitment to the flourishing of all people. The church that ignores public health has ignored a core dimension of justice.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('What the Early Church Practiced That We Won''t', 'early-church-practiced', 'The early church''s radical economic sharing was not optional but central to its witness.', 'The early church practiced radical economic sharing. It was not optional but central to its witness. The contemporary church has largely abandoned this practice.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

-- SECTION 10: LITERACY, IMAGINATION & THE PROPHETIC MANIFESTO (91-100)
('Literacy as Justice', 'literacy-as-justice', 'Literacy is not just an individual skill but a justice issue rooted in the ability to participate in society.', 'Literacy is not just an individual skill but a justice issue rooted in the ability to participate in society. The church that ignores literacy has ignored a core dimension of justice.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('The School-to-Prison Pipeline', 'school-to-prison-pipeline', 'The criminalization of poor youth is a justice issue that the church has largely ignored.', 'The school-to-prison pipeline is a justice issue. The criminalization of poor youth is a system that the church has largely ignored. The church must speak prophetically about this.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

('The Theology of Clean Air', 'theology-clean-air', 'Clean air is not a luxury but a requirement for human flourishing rooted in God''s provision.', 'Clean air is not a luxury but a requirement for human flourishing rooted in God''s provision. Environmental justice includes the right to breathe clean air.', 'Prophetic Justice', 'James Bell', 1, 6, 'general', 'general', NOW(), NOW()),

('Foster Care and the Church''s Unfinished Mandate', 'foster-care-unfinished-mandate', 'The church''s commitment to orphans is incomplete without addressing the systems that create orphans.', 'The church''s commitment to orphans is incomplete without addressing the systems that create orphans. Foster care is a justice issue rooted in God''s identification with the vulnerable.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

('Jeremiah''s Letter to the Exiles', 'jeremiah-letter-exiles', 'Jeremiah''s call to seek the welfare of the city applies to contemporary churches in their contexts.', 'Jeremiah called the exiles to seek the welfare of the city. This call applies to contemporary churches in their contexts. The church is called to seek the welfare of the city.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('The Church and Food Insecurity', 'church-food-insecurity', 'Food insecurity is a justice issue that affects millions in the wealthiest nation in history.', 'Food insecurity is a justice issue that affects millions in the wealthiest nation in history. The church that prays for daily bread while being silent about food insecurity has separated theology from reality.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

('Gender-Based Violence', 'gender-based-violence', 'Gender-based violence is a justice issue that the church has enabled through patriarchal theology.', 'Gender-based violence is a justice issue that the church has enabled through patriarchal theology. The church must repent and become a place of safety for survivors.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW()),

('The Theology of Enough', 'theology-of-enough', 'God''s provision is enough. The pursuit of endless accumulation is idolatry.', 'God''s provision is enough. The pursuit of endless accumulation is idolatry. The church that teaches the theology of enough will transform the world.', 'Prophetic Justice', 'James Bell', 1, 6, 'general', 'general', NOW(), NOW()),

('The Prophetic Imagination', 'prophetic-imagination', 'The ability to imagine a different world is essential to prophetic witness.', 'The prophetic imagination is the ability to imagine a different world. It is essential to prophetic witness. The church must cultivate the prophetic imagination.', 'Prophetic Justice', 'James Bell', 1, 7, 'general', 'general', NOW(), NOW()),

('Do Justice, Love Mercy, Walk Humbly: A Manifesto', 'do-justice-manifesto', 'A call to the church to return to the core mandate of Micah 6:8.', 'Do justice. Love mercy. Walk humbly with your God. This is the core mandate of Micah 6:8. This is the call to the church. This is the prophetic manifesto.', 'Prophetic Justice', 'James Bell', 1, 8, 'general', 'general', NOW(), NOW());
